#ifndef __FAKE_KCONFIG__
#define __FAKE_KCONFIG__

#define BL_NORDIC_COMPANY_ID 0x0059
#define CONFIG_BL_COMPOSITION_COMPANY_ID BL_NORDIC_COMPANY_ID

#define CONFIG_BL_MESH_PROVISIONING_STACK_SIZE 2048
#define CONFIG_BL_MESH_PROVISIONING_PRIORITY -2

#define CONFIG_SENSIBLE_DATA 1

#endif /* __FAKE_KCONFIG__ */